config/routes.rb
Rails.application.routes.draw do
  resources :albums do
    resources :reviews
  end
  
  devise_for :users

  root 'application#index'
  get '/myalbums' => 'albums#myalbums'

end

app/models/album.rb
class Album < ApplicationRecord
    validates :title, :presence => true
    validates :artist, :presence => true
    validates :description, :presence => true
    
    has_many :reviews
    belongs_to :user
    
    def self.search(search)
        where("title ILIKE ? OR artist ILIKE ?", "%#{search}%", "%#{search}%") 
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
    validates :reviewer, :presence => true
    validates :body, :presence => true
    belongs_to :album
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :albums
  has_many :reviews
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create, :index]
  helper_method :sort_column, :sort_direction
  add_flash_types :error
  before_filter :authenticate_user!

  # GET /albums
  # GET /albums.json
  def index
    if params[:search]
      @albums = Album.search(params[:search]).order("title ASC")
    else
      @albums = Album.order(sort_column + " " + sort_direction)
    end
  end
  
  def myalbums
    @albums = current_user.albums.order(sort_column + " " + sort_direction)
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)
    @album.user = current_user

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    if current_user == @album.user
      @album.destroy
      respond_to do |format|
        format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html {redirect_to albums_url, error: 'Unable to remove album: only the original creator can remove an album.'}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title, :artist, :description)
    end
    
    def sort_column
        params[:sort] || "title"
    end
    
    def sort_direction
      params[:direction] || "asc"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :authenticate_user!

def index
    redirect_to albums_path
    @title = ""
    @intro = ""
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  
  def create
    @album = Album.find(params[:album_id])
    @review = @album.reviews.create(review_params)
    redirect_to album_path(@album)
  end
 
  def destroy
    @album = Album.find(params[:album_id])
    @review = @album.reviews.find(params[:id])
    @review.destroy
    redirect_to album_path(@album)
  end
    
  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:reviewer, :body)
    end 
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def sortable(column, title = nil)
        title ||= column.titleize
        direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
        link_to title, :sort => column, :direction => direction
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/albums/_form.html.erb
<%= form_for(album) do |f| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :artist %>
    <%= f.text_field :artist %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Albums</h1>
  <div class="tablebody">
  <p>Sort by: <%= sortable "Title"%> 
  | <%= sortable "Artist"%></p>

  <table align="center">
    <thead>
    <tr>
      <th>Title</th>
      <th>Artist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.title %></td>
        <td><%= album.artist %></td>
        <td><%= link_to 'More Information', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <% if current_user == album.user%>
        <td><%= link_to 'Delete', album, method: :delete, data: { confirm: 'Are you sure you want to delete this album?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Album', new_album_path %>

app/views/albums/myalbums.html.erb
<p id="notice"><%= notice %></p>

<h1>Albums</h1>
  
  <div class="tablebody">
  <p>Sort by: <%= sortable "Title"%> 
  | <%= sortable "Artist"%></p>


  <table align="center">
    <thead>
    <tr>
      <th>Title</th>
      <th>Artist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.title %></td>
        <td><%= album.artist %></td>
        <td><%= link_to 'More Information', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <% if current_user == album.user%>
        <td><%= link_to 'Delete', album, method: :delete, data: { confirm: 'Are you sure you want to delete this album?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

<br>

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New Album</h1>
<p>
    
</p>
<div class = "create">
<%= render 'form', album: @album %>

<%= link_to 'Back', albums_path %>
</div>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>
<div class = "show">
<h2>
  <strong>Title:</strong>
  <%= @album.title %>
</h2>
<p>
  
</p>

<h3>
  <strong>Artist:</strong>
  <%= @album.artist %>
</h3>
<p>
  
</p>

<h4>
  <strong>Description:</strong>
  <%= @album.description %>
</h4>
</div>
<p>
  
</p>

<div class = "reviews">
<h2>Reviews</h2>
<% @album.reviews.each do |review| %>
  <h5>
    <b>Name:</b>
    <%= review.reviewer %>
  </h5>
 
  <h5>
    <b>Review:</b>
    <%= review.body %>
  </h5>
  <p>
  <%= link_to 'Delete Review', [review.album, review], data: { confirm: 'Are you sure you want to delete this review?'},
               method: :delete %>
  </p>
<% end %>
</div>

<p>
  
</p>
<div class="addreviews">
<h2>Add a review:</h2>
<%= form_for([@album, @album.reviews.build]) do |f| %>
  <div class="field">
    <%= f.label :reviewer, 'Name' %><br />
    <%= f.text_field :reviewer %>
  </div>
  <div class="field">
    <%= f.label :body, 'Review' %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>
</div>

app/views/application/index.html.erb
<h1><%= @title %></h1>
<h2><%= @intro %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'%>
    <%= stylesheet_link_tag    "https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"%>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
    
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar" aria-expanded-"false" aria-controls="navbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span> 
          </button>
          <a class="navbar-brand" href="/">Music Album Reviews</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <li><a href="/albums">Home</a></li>
            <li><a href="/myalbums">My Music</a></li>
            <li><a href="/albums/new">Add New Music</a></li>
          </ul>
          <ul class="nav navbar-form navbar-right">
            <div class="form-group">
              <%= form_tag(albums_path, :method => "get", id: "search-bar") do %>
                <%= search_field_tag :search, params[:search], placeholder: "Search..." %>
              <% end %>
            </div>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: 'delete' %></li>
            <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <% end %>
          </ul>  
        </div>
    </nav>
    
    <%= yield %>
    
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  </body>
</html>